---
application:
  name: "rs2-webbot"
  project: "RS2-WebBot"
  organization: "QoveryCommunity"
  cpu: 256m
  publicly_accessible: true
  port: 6969
  storage:
  - name: "data"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/data"
databases:
- type: "MYSQL"
  name: "RS2Database"
  version: "8.0"
routers:
- name: "main-rs2-webbot"
  routes:
  - application_name: "rs2-webbot"
    paths:
    - "/"
